// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PasswordManager.API.Context;

#nullable disable

namespace PasswordManager.API.Migrations
{
    [DbContext(typeof(PasswordManagerDBContext))]
    partial class PasswordManagerDBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.10");

            modelBuilder.Entity("PasswordManager.API.AppUser", b =>
                {
                    b.Property<Guid>("Identifier")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("entraId")
                        .HasColumnType("TEXT");

                    b.HasKey("Identifier");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Identifier = new Guid("00000000-0000-0000-0000-000000000001"),
                            Email = "",
                            entraId = new Guid("00000000-0000-0000-0000-000000000001")
                        });
                });

            modelBuilder.Entity("PasswordManager.API.Objects.Vault", b =>
                {
                    b.Property<Guid>("Identifier")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("CreatorIdentifier")
                        .HasColumnType("TEXT");

                    b.Property<string>("EncryptKey")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsShared")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("LastUpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("MasterSalt")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<string>("Salt")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("Identifier");

                    b.HasIndex("CreatorIdentifier");

                    b.ToTable("Vaults");
                });

            modelBuilder.Entity("PasswordManager.API.Objects.VaultLog", b =>
                {
                    b.Property<Guid>("Identifier")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Date")
                        .HasColumnType("TEXT");

                    b.Property<string>("EncryptedData")
                        .IsRequired()
                        .HasMaxLength(4096)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("VaultIdentifier")
                        .HasColumnType("TEXT");

                    b.HasKey("Identifier");

                    b.HasIndex("VaultIdentifier");

                    b.ToTable("VaultLogs");
                });

            modelBuilder.Entity("PasswordManager.API.Objects.VaultUserAccess", b =>
                {
                    b.Property<Guid>("VaultIdentifier")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("UserIdentifier")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsAdmin")
                        .HasColumnType("INTEGER");

                    b.HasKey("VaultIdentifier", "UserIdentifier");

                    b.HasIndex("UserIdentifier");

                    b.ToTable("VaultUserAccesses");
                });

            modelBuilder.Entity("PasswordManager.API.VaultEntry", b =>
                {
                    b.Property<Guid>("Identifier")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("CreatorIdentifier")
                        .HasColumnType("TEXT");

                    b.Property<string>("CypherData")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("TEXT");

                    b.Property<string>("CypherPassword")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<string>("IVData")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("IVPassword")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("LastUpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("TagData")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("TagPasswords")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("VaultIdentifier")
                        .HasColumnType("TEXT");

                    b.HasKey("Identifier");

                    b.HasIndex("CreatorIdentifier");

                    b.HasIndex("VaultIdentifier");

                    b.ToTable("VaultEntries");
                });

            modelBuilder.Entity("PasswordManager.API.Objects.Vault", b =>
                {
                    b.HasOne("PasswordManager.API.AppUser", "Creator")
                        .WithMany("Vaults")
                        .HasForeignKey("CreatorIdentifier")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Creator");
                });

            modelBuilder.Entity("PasswordManager.API.Objects.VaultLog", b =>
                {
                    b.HasOne("PasswordManager.API.Objects.Vault", "Vault")
                        .WithMany("Logs")
                        .HasForeignKey("VaultIdentifier")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Vault");
                });

            modelBuilder.Entity("PasswordManager.API.Objects.VaultUserAccess", b =>
                {
                    b.HasOne("PasswordManager.API.AppUser", "User")
                        .WithMany("VaultAccesses")
                        .HasForeignKey("UserIdentifier")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PasswordManager.API.Objects.Vault", "Vault")
                        .WithMany("UserAccesses")
                        .HasForeignKey("VaultIdentifier")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");

                    b.Navigation("Vault");
                });

            modelBuilder.Entity("PasswordManager.API.VaultEntry", b =>
                {
                    b.HasOne("PasswordManager.API.AppUser", "Creator")
                        .WithMany("Entries")
                        .HasForeignKey("CreatorIdentifier")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PasswordManager.API.Objects.Vault", "Vault")
                        .WithMany("Entries")
                        .HasForeignKey("VaultIdentifier")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Creator");

                    b.Navigation("Vault");
                });

            modelBuilder.Entity("PasswordManager.API.AppUser", b =>
                {
                    b.Navigation("Entries");

                    b.Navigation("VaultAccesses");

                    b.Navigation("Vaults");
                });

            modelBuilder.Entity("PasswordManager.API.Objects.Vault", b =>
                {
                    b.Navigation("Entries");

                    b.Navigation("Logs");

                    b.Navigation("UserAccesses");
                });
#pragma warning restore 612, 618
        }
    }
}
